apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: arc-sparks
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/danielsollondon/arc-sparks
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: arc-sparks
  namespace: flux-system
spec:
  interval: 30s
  approvePlan: "auto"
  path: ./eks
  sourceRef:
    kind: GitRepository
    name: arc-sparks
    namespace: flux-system
  envFrom:
      - name: access_key
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: access_key
            optional: false 
      - name: secret_key
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: secret_key
            optional: false